import type { Category, Book, StoreLocation } from './types';

export const categories: Category[] = [
  { id: 'bhagavad-gita', name: 'भगवद्गीता', description: 'दिव्य गीतेची भाष्ये आणि भाषांतरे', image: 'https://images.pexels.com/photos/13207104/pexels-photo-13207104.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'vedas', name: 'वेद', description: 'शाश्वत ज्ञान — ऋग्, यजुर्, साम, अथर्व', image: 'https://images.pexels.com/photos/18062018/pexels-photo-18062018.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'upanishads', name: 'उपनिषदे', description: 'वैदिक विचारांचा तात्त्विक मुकुट', image: 'https://images.pexels.com/photos/11388027/pexels-photo-11388027.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'puranas', name: 'पुराणे', description: 'प्राचीन कथा आणि पवित्र आख्यायिका', image: 'https://images.pexels.com/photos/15235034/pexels-photo-15235034.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'ramayana', name: 'रामायण', description: 'परंपरांमधील रामायण महाकाव्य', image: 'https://images.pexels.com/photos/35341456/pexels-photo-35341456.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'mahabharata', name: 'महाभारत', description: 'भारतांचे महाकाव्य', image: 'https://images.pexels.com/photos/28672541/pexels-photo-28672541.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'hindu-philosophy', name: 'हिंदू तत्त्वज्ञान', description: 'दर्शने आणि विचार प्रवाह', image: 'https://images.pexels.com/photos/28850397/pexels-photo-28850397.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'vedanta', name: 'वेदांत', description: 'वैदिक ज्ञानाचा शेवट — अद्वैत आणि पुढे', image: 'https://images.pexels.com/photos/28793885/pexels-photo-28793885.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'bhakti', name: 'भक्ती', description: 'भक्ती साहित्य आणि संत-कवी परंपरा', image: 'https://images.pexels.com/photos/34431714/pexels-photo-34431714.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'mantras-stotras', name: 'मंत्र व स्तोत्रे', description: 'पवित्र मंत्र, स्तोत्रे आणि आवाहन', image: 'https://images.pexels.com/photos/1656369/pexels-photo-1656369.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'puja-rituals', name: 'पूजा व विधी', description: 'पूजा, विधी आणि संस्कारांचे मार्गदर्शन', image: 'https://images.pexels.com/photos/14266576/pexels-photo-14266576.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'sanskrit-literature', name: 'संस्कृत साहित्य', description: 'शास्त्रीय काव्य, नाटक आणि व्याकरण', image: 'https://images.pexels.com/photos/35098073/pexels-photo-35098073.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'astrology', name: 'ज्योतिष', description: 'ज्योतिष — वैदिक ज्योतिष आणि खगोलशास्त्र', image: 'https://images.pexels.com/photos/38976177/pexels-photo-38976177.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'ayurveda-wellness', name: 'आयुर्वेद व स्वास्थ्य', description: 'जीवन आणि उपचारांचे शास्त्र', image: 'https://images.pexels.com/photos/38374178/pexels-photo-38374178.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'spirituality', name: 'अध्यात्म', description: 'अंतर्जीवन, ध्यान आणि आत्मसाक्षात्कार', image: 'https://images.pexels.com/photos/31275659/pexels-photo-31275659.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'childrens-spiritual', name: 'बाल अध्यात्मिक पुस्तके', description: 'लहान वाचकांसाठी देव, नायक आणि मूल्यांच्या कथा', image: 'https://images.pexels.com/photos/12851459/pexels-photo-12851459.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
];

export const books: Book[] = [
  {
    id: 'bg-001',
    title: 'Srimad Bhagavad Gita',
    author: 'Swami Chinmayananda',
    publication: 'Pradnyesh Prakashan',
    language: 'Marathi',
    price: 450,
    originalPrice: 550,
    category: 'bhagavad-gita',
    coverColor: '#6B4A2F',
    coverAccent: '#C9A227',
    description: 'भगवद्गीतेवर सर्वसमावेशक मराठी भाष्य, श्लोकांनुसार, आधुनिक वाचकासाठी कृष्णांचे शाश्वत ज्ञान प्रकाशित करणारे.',
    pages: 620,
    format: 'Hardcover',
    year: '2019',
    featured: true,
  },
  {
    id: 'bg-002',
    title: 'Bhagavad Gita As It Is',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    publication: 'Pradnyesh Prakashan',
    language: 'Hindi',
    price: 650,
    category: 'bhagavad-gita',
    coverColor: '#8B4513',
    coverAccent: '#D4AF37',
    description: 'संपूर्ण भगवद्गीता संस्कृत श्लोक, हिंदी भाषांतर आणि विस्तृत टीकेसहित.',
    pages: 880,
    format: 'Hardcover',
    year: '2020',
    featured: true,
  },
  {
    id: 'veda-001',
    title: 'Rigveda Samhita',
    author: 'Pt. Damodar Satwalekar',
    publication: 'Pradnyesh Prakashan',
    language: 'Sanskrit',
    price: 1200,
    category: 'vedas',
    coverColor: '#3D2B1F',
    coverAccent: '#B8860B',
    description: 'ऋग्वेद संहिता संस्कृत मजकूर आणि निवडक पदार्थांसह. वैदिक साहित्याच्या गंभीर विद्यार्थ्यांसाठी एक शास्त्रीय संस्करण.',
    pages: 1100,
    format: 'Hardcover',
    year: '2018',
    featured: true,
  },
  {
    id: 'upan-001',
    title: 'Isha Upanishad',
    author: 'Sri Aurobindo',
    publication: 'Pradnyesh Prakashan',
    language: 'English',
    price: 350,
    category: 'upanishads',
    coverColor: '#4A3526',
    coverAccent: '#C0AB8E',
    description: 'श्री अरविंदांचे ईश उपनिषदावरील भाष्य, दैवी आणि जगाच्या एकात्मतेचा शोध घेणारे.',
    pages: 280,
    format: 'Paperback',
    year: '2021',
  },
  {
    id: 'puran-001',
    title: 'Srimad Bhagavatam',
    author: 'Kamala Subramaniam',
    publication: 'Pradnyesh Prakashan',
    language: 'Hindi',
    price: 850,
    originalPrice: 950,
    category: 'puranas',
    coverColor: '#6B4A2F',
    coverAccent: '#E0C560',
    description: 'सोप्या हिंदीमध्ये भागवताचे संपूर्ण पुनर्कथन, सर्व बारा स्कंधांचा समावेश.',
    pages: 950,
    format: 'Hardcover',
    year: '2017',
    featured: true,
  },
  {
    id: 'ram-001',
    title: 'Shri Ramcharitmanas',
    author: 'Goswami Tulsidas',
    publication: 'Pradnyesh Prakashan',
    language: 'Hindi',
    price: 750,
    category: 'ramayana',
    coverColor: '#9A5A12',
    coverAccent: '#D4AF37',
    description: 'संपूर्ण हिंदी भाष्यासह रामचरितमानस, दैनिक पठण आणि अभ्यासासाठी आदर्श.',
    pages: 1050,
    format: 'Hardcover',
    year: '2019',
    featured: true,
  },
  {
    id: 'maha-001',
    title: 'Mahabharata',
    author: 'Kamala Subramaniam',
    publication: 'Pradnyesh Prakashan',
    language: 'English',
    price: 950,
    category: 'mahabharata',
    coverColor: '#3D2B1F',
    coverAccent: '#B8860B',
    description: 'महाभारताचे संपूर्ण आणि सुलभ पुनर्कथन, महाकाव्याची खोली आणि नाट्य व्यक्त करणारे.',
    pages: 780,
    format: 'Hardcover',
    year: '2018',
  },
  {
    id: 'veda-002',
    title: 'Yajurveda Samhita',
    author: 'Pt. Damodar Satwalekar',
    publication: 'Pradnyesh Prakashan',
    language: 'Sanskrit',
    price: 950,
    category: 'vedas',
    coverColor: '#4A3526',
    coverAccent: '#C9A227',
    description: 'यजुर्वेद संहिता संस्कृत मजकुरासह, विधी आणि शास्त्रीय उपयोगासाठी तयार केलेली.',
    pages: 720,
    format: 'Hardcover',
    year: '2016',
  },
  {
    id: 'bhakti-001',
    title: 'Sant Sahitya Sangraha',
    author: 'Various Saints',
    publication: 'Pradnyesh Prakashan',
    language: 'Marathi',
    price: 400,
    category: 'bhakti',
    coverColor: '#8B7355',
    coverAccent: '#D4AF37',
    description: 'महाराष्ट्राच्या संत परंपरेतील अभंग आणि लेखनांचा संग्रह — ज्ञानेश्वर, तुकाराम, नामदेव आणि इतर.',
    pages: 520,
    format: 'Paperback',
    year: '2020',
    featured: true,
  },
  {
    id: 'mantra-001',
    title: 'Mantra Pushpam',
    author: 'Veda Pathashala',
    publication: 'Pradnyesh Prakashan',
    language: 'Sanskrit',
    price: 250,
    category: 'mantras-stotras',
    coverColor: '#6B4A2F',
    coverAccent: '#E0C560',
    description: 'दैनिक पठणासाठी आवश्यक वैदिक मंत्र आणि स्तोत्रांचा संग्रह, स्पष्ट संस्कृत मजकुरासह.',
    pages: 180,
    format: 'Paperback',
    year: '2022',
  },
  {
    id: 'vedanta-001',
    title: 'Vedanta Sara',
    author: 'Sadhananda Swami',
    publication: 'Pradnyesh Prakashan',
    language: 'English',
    price: 300,
    category: 'vedanta',
    coverColor: '#3D2B1F',
    coverAccent: '#C0AB8E',
    description: 'अद्वैत वेदांतावर एक उत्कृष्ट परिचयात्मक ग्रंथ, वेदांतिक तत्त्वज्ञानाची मूलभूत तत्त्वे सादर करणारा.',
    pages: 240,
    format: 'Paperback',
    year: '2021',
  },
  {
    id: 'ayur-001',
    title: 'Ayurveda Siddhanta',
    author: 'Vaidya Atreya',
    publication: 'Pradnyesh Prakashan',
    language: 'Marathi',
    price: 550,
    category: 'ayurveda-wellness',
    coverColor: '#6B4A2F',
    coverAccent: '#C8741A',
    description: 'मराठीमध्ये आयुर्वेदाची मूलभूत तत्त्वे, दोष, धातू आणि बेसिक उपचार पद्धतींचा समावेश.',
    pages: 420,
    format: 'Hardcover',
    year: '2019',
  },
  {
    id: 'astro-001',
    title: 'Jyotisha Vigyan',
    author: 'Pt. Ramesh Shastri',
    publication: 'Pradnyesh Prakashan',
    language: 'Marathi',
    price: 600,
    category: 'astrology',
    coverColor: '#2A1B12',
    coverAccent: '#B8860B',
    description: 'राशी, ग्रह, भाव आणि बेसिक कुंडली वाचनासह वैदिक ज्योतिषाची ओळख.',
    pages: 480,
    format: 'Hardcover',
    year: '2020',
  },
  {
    id: 'puja-001',
    title: 'Pooja Vidhi Sangraha',
    author: 'Pt. Anand Joshi',
    publication: 'Pradnyesh Prakashan',
    language: 'Marathi',
    price: 350,
    category: 'puja-rituals',
    coverColor: '#9A5A12',
    coverAccent: '#E0C560',
    description: 'मराठीमध्ये दैनिक आणि सणांच्या पूजांचे संपूर्ण मार्गदर्शक, मंत्र आणि टप्पाटप्पाने सूचनांसह.',
    pages: 320,
    format: 'Paperback',
    year: '2022',
  },
  {
    id: 'sansk-001',
    title: 'Kavya Prakash',
    author: 'Mammata Bhatta',
    publication: 'Pradnyesh Prakashan',
    language: 'Sanskrit',
    price: 500,
    category: 'sanskrit-literature',
    coverColor: '#4A3526',
    coverAccent: '#C9A227',
    description: 'संस्कृत काव्यशास्त्र (अलंकार शास्त्र) वर एक मूलभूत ग्रंथ, शास्त्रीय साहित्याच्या विद्यार्थ्यांसाठी आवश्यक.',
    pages: 380,
    format: 'Hardcover',
    year: '2017',
  },
  {
    id: 'child-001',
    title: 'Bal Bharat Katha',
    author: 'Sudha Murty',
    publication: 'Pradnyesh Prakashan',
    language: 'Marathi',
    price: 280,
    category: 'childrens-spiritual',
    coverColor: '#8B7355',
    coverAccent: '#F0A850',
    description: 'सोप्या मराठीमध्ये भारतीय पौराणिक कथांचे बालकांसाठी पुनर्कथन, नैतिक शिक्षणांसह.',
    pages: 160,
    format: 'Paperback',
    year: '2023',
    featured: true,
  },
  {
    id: 'spirit-001',
    title: 'Adhyatma Jnan',
    author: 'Swami Swaroopananda',
    publication: 'Pradnyesh Prakashan',
    language: 'Marathi',
    price: 400,
    category: 'spirituality',
    coverColor: '#3D2B1F',
    coverAccent: '#C0AB8E',
    description: 'मराठी परंपरेतील अध्यात्मिक ज्ञानाचा शोध, ध्यान, स्व-चौकशी आणि भक्तीचा समावेश.',
    pages: 300,
    format: 'Paperback',
    year: '2021',
  },
  {
    id: 'phil-001',
    title: 'Nyaya Darshana',
    author: 'Pt. Dinesh Chandra',
    publication: 'Pradnyesh Prakashan',
    language: 'Hindi',
    price: 450,
    category: 'hindu-philosophy',
    coverColor: '#2A1B12',
    coverAccent: '#B8860B',
    description: 'न्याय संप्रदायातील भारतीय तत्त्वज्ञानाची ओळख, तर्कशास्त्र, ज्ञानमीमांसा आणि वादविवादाचा समावेश.',
    pages: 340,
    format: 'Hardcover',
    year: '2018',
  },
];

export const storeLocations: StoreLocation[] = [
  {
    name: 'अशोक अनंत नेरळेकर बुकसेलर्स',
    address: 'बुधवार पेठ, पुणे',
    city: 'पुणे',
    state: 'महाराष्ट्र',
    phone: '9309526618',
    whatsapp: '9309526618',
    email: 'nerlekarbooksellers@gmail.com',
  },
  {
    name: 'श्री कृपा एंटरप्रायझेस',
    address: 'कसबा पेठ, पुणे',
    city: 'पुणे',
    state: 'महाराष्ट्र',
    phone: '9309526618',
    whatsapp: '9309526618',
    email: 'nerlekarbooksellers@gmail.com',
  },
];

export const languages: { name: string; native: string; description: string }[] = [
  { name: 'Marathi', native: 'मराठी', description: 'महाराष्ट्राच्या संत-कवींची आणि भक्ती साहित्याची भाषा' },
  { name: 'Hindi', native: 'हिन्दी', description: 'भारतीय अध्यात्मिक ग्रंथांची सर्वाधिक बोलली जाणारी भाषा' },
  { name: 'Sanskrit', native: 'संस्कृतम्', description: 'वेद आणि शास्त्रांची प्राचीन पवित्र भाषा' },
];

export const publications = ['प्रज्ञेश प्रकाशन', 'इतर प्रकाशक'];
