import type { Category, Book, StoreLocation } from './types';

export const categories: Category[] = [
  { id: 'bhagavad-gita', name: 'Bhagavad Gita', description: 'Commentaries and translations of the divine song', image: 'https://images.pexels.com/photos/13207104/pexels-photo-13207104.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'vedas', name: 'Vedas', description: 'The eternal knowledge — Rig, Yajur, Sama, Atharva', image: 'https://images.pexels.com/photos/18062018/pexels-photo-18062018.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'upanishads', name: 'Upanishads', description: 'The philosophical crown of Vedic thought', image: 'https://images.pexels.com/photos/11388027/pexels-photo-11388027.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'puranas', name: 'Puranas', description: 'Ancient lore and sacred narratives', image: 'https://images.pexels.com/photos/15235034/pexels-photo-15235034.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'ramayana', name: 'Ramayana', description: 'The epic of Rama across traditions', image: 'https://images.pexels.com/photos/35341456/pexels-photo-35341456.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'mahabharata', name: 'Mahabharata', description: 'The great epic of the Bharatas', image: 'https://images.pexels.com/photos/28672541/pexels-photo-28672541.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'hindu-philosophy', name: 'Hindu Philosophy', description: 'Darshanas and schools of thought', image: 'https://images.pexels.com/photos/28850397/pexels-photo-28850397.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'vedanta', name: 'Vedanta', description: 'The end of Vedic wisdom — Advaita and beyond', image: 'https://images.pexels.com/photos/28793885/pexels-photo-28793885.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'bhakti', name: 'Bhakti', description: 'Devotional literature and saint-poet traditions', image: 'https://images.pexels.com/photos/34431714/pexels-photo-34431714.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'mantras-stotras', name: 'Mantras & Stotras', description: 'Sacred chants, hymns, and invocations', image: 'https://images.pexels.com/photos/1656369/pexels-photo-1656369.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'puja-rituals', name: 'Puja & Rituals', description: 'Guides to worship, rites, and ceremonies', image: 'https://images.pexels.com/photos/14266576/pexels-photo-14266576.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'sanskrit-literature', name: 'Sanskrit Literature', description: 'Classical poetry, drama, and grammar', image: 'https://images.pexels.com/photos/35098073/pexels-photo-35098073.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'astrology', name: 'Astrology', description: 'Jyotisha — Vedic astrology and astronomy', image: 'https://images.pexels.com/photos/38976177/pexels-photo-38976177.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'ayurveda-wellness', name: 'Ayurveda & Wellness', description: 'The science of life and healing', image: 'https://images.pexels.com/photos/38374178/pexels-photo-38374178.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'spirituality', name: 'Spirituality', description: 'Inner life, meditation, and self-realisation', image: 'https://images.pexels.com/photos/31275659/pexels-photo-31275659.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
  { id: 'childrens-spiritual', name: "Children's Spiritual Books", description: 'Stories of gods, heroes, and values for young readers', image: 'https://images.pexels.com/photos/12851459/pexels-photo-12851459.jpeg?auto=compress&cs=tinysrgb&h=400&w=600' },
];

export const books: Book[] = [
  {
    id: 'bg-001',
    title: 'Srimad Bhagavad Gita',
    author: 'Swami Chinmayananda',
    publication: 'Pradnyesh Prakashan',
    language: 'Marathi',
    price: 450,
    originalPrice: 550,
    category: 'bhagavad-gita',
    coverColor: '#6B4A2F',
    coverAccent: '#C9A227',
    description: 'A comprehensive Marathi commentary on the Bhagavad Gita, verse by verse, illuminating the timeless wisdom of Krishna for the modern reader.',
    pages: 620,
    format: 'Hardcover',
    year: '2019',
    featured: true,
  },
  {
    id: 'bg-002',
    title: 'Bhagavad Gita As It Is',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    publication: 'Pradnyesh Prakashan',
    language: 'Hindi',
    price: 650,
    category: 'bhagavad-gita',
    coverColor: '#8B4513',
    coverAccent: '#D4AF37',
    description: 'The complete Bhagavad Gita with Sanskrit verses, Hindi translation, and elaborate purports.',
    pages: 880,
    format: 'Hardcover',
    year: '2020',
    featured: true,
  },
  {
    id: 'veda-001',
    title: 'Rigveda Samhita',
    author: 'Pt. Damodar Satwalekar',
    publication: 'Pradnyesh Prakashan',
    language: 'Sanskrit',
    price: 1200,
    category: 'vedas',
    coverColor: '#3D2B1F',
    coverAccent: '#B8860B',
    description: 'The Rigveda Samhita with Sanskrit text and select padarthas. A scholarly edition for serious students of Vedic literature.',
    pages: 1100,
    format: 'Hardcover',
    year: '2018',
    featured: true,
  },
  {
    id: 'upan-001',
    title: 'Isha Upanishad',
    author: 'Sri Aurobindo',
    publication: 'Pradnyesh Prakashan',
    language: 'English',
    price: 350,
    category: 'upanishads',
    coverColor: '#4A3526',
    coverAccent: '#C0AB8E',
    description: 'Sri Aurobindo\'s commentary on the Isha Upanishad, exploring the unity of the divine and the world.',
    pages: 280,
    format: 'Paperback',
    year: '2021',
  },
  {
    id: 'puran-001',
    title: 'Srimad Bhagavatam',
    author: 'Kamala Subramaniam',
    publication: 'Pradnyesh Prakashan',
    language: 'Hindi',
    price: 850,
    originalPrice: 950,
    category: 'puranas',
    coverColor: '#6B4A2F',
    coverAccent: '#E0C560',
    description: 'A complete retelling of the Bhagavatam in accessible Hindi, covering all twelve cantos.',
    pages: 950,
    format: 'Hardcover',
    year: '2017',
    featured: true,
  },
  {
    id: 'ram-001',
    title: 'Shri Ramcharitmanas',
    author: 'Goswami Tulsidas',
    publication: 'Pradnyesh Prakashan',
    language: 'Hindi',
    price: 750,
    category: 'ramayana',
    coverColor: '#9A5A12',
    coverAccent: '#D4AF37',
    description: 'The Ramcharitmanas with complete Hindi commentary, ideal for daily recitation and study.',
    pages: 1050,
    format: 'Hardcover',
    year: '2019',
    featured: true,
  },
  {
    id: 'maha-001',
    title: 'Mahabharata',
    author: 'Kamala Subramaniam',
    publication: 'Pradnyesh Prakashan',
    language: 'English',
    price: 950,
    category: 'mahabharata',
    coverColor: '#3D2B1F',
    coverAccent: '#B8860B',
    description: 'A complete and accessible retelling of the Mahabharata, capturing the epic\'s depth and drama.',
    pages: 780,
    format: 'Hardcover',
    year: '2018',
  },
  {
    id: 'veda-002',
    title: 'Yajurveda Samhita',
    author: 'Pt. Damodar Satwalekar',
    publication: 'Pradnyesh Prakashan',
    language: 'Sanskrit',
    price: 950,
    category: 'vedas',
    coverColor: '#4A3526',
    coverAccent: '#C9A227',
    description: 'The Yajurveda Samhita with Sanskrit text, prepared for ritual and scholarly use.',
    pages: 720,
    format: 'Hardcover',
    year: '2016',
  },
  {
    id: 'bhakti-001',
    title: 'Sant Sahitya Sangraha',
    author: 'Various Saints',
    publication: 'Pradnyesh Prakashan',
    language: 'Marathi',
    price: 400,
    category: 'bhakti',
    coverColor: '#8B7355',
    coverAccent: '#D4AF37',
    description: 'A collection of abhangs and writings from the Maharashtra saint tradition — Dnyaneshwar, Tukaram, Namdev, and others.',
    pages: 520,
    format: 'Paperback',
    year: '2020',
    featured: true,
  },
  {
    id: 'mantra-001',
    title: 'Mantra Pushpam',
    author: 'Veda Pathashala',
    publication: 'Pradnyesh Prakashan',
    language: 'Sanskrit',
    price: 250,
    category: 'mantras-stotras',
    coverColor: '#6B4A2F',
    coverAccent: '#E0C560',
    description: 'A collection of essential Vedic mantras and stotras for daily recitation, with clear Sanskrit text.',
    pages: 180,
    format: 'Paperback',
    year: '2022',
  },
  {
    id: 'vedanta-001',
    title: 'Vedanta Sara',
    author: 'Sadhananda Swami',
    publication: 'Pradnyesh Prakashan',
    language: 'English',
    price: 300,
    category: 'vedanta',
    coverColor: '#3D2B1F',
    coverAccent: '#C0AB8E',
    description: 'A classic introductory text on Advaita Vedanta, presenting the essentials of Vedantic philosophy.',
    pages: 240,
    format: 'Paperback',
    year: '2021',
  },
  {
    id: 'ayur-001',
    title: 'Ayurveda Siddhanta',
    author: 'Vaidya Atreya',
    publication: 'Pradnyesh Prakashan',
    language: 'Marathi',
    price: 550,
    category: 'ayurveda-wellness',
    coverColor: '#6B4A2F',
    coverAccent: '#C8741A',
    description: 'Fundamental principles of Ayurveda in Marathi, covering doshas, dhatus, and basic treatment approaches.',
    pages: 420,
    format: 'Hardcover',
    year: '2019',
  },
  {
    id: 'astro-001',
    title: 'Jyotisha Vigyan',
    author: 'Pt. Ramesh Shastri',
    publication: 'Pradnyesh Prakashan',
    language: 'Marathi',
    price: 600,
    category: 'astrology',
    coverColor: '#2A1B12',
    coverAccent: '#B8860B',
    description: 'An introduction to Vedic astrology covering rashis, grahas, bhavas, and basic chart interpretation.',
    pages: 480,
    format: 'Hardcover',
    year: '2020',
  },
  {
    id: 'puja-001',
    title: 'Pooja Vidhi Sangraha',
    author: 'Pt. Anand Joshi',
    publication: 'Pradnyesh Prakashan',
    language: 'Marathi',
    price: 350,
    category: 'puja-rituals',
    coverColor: '#9A5A12',
    coverAccent: '#E0C560',
    description: 'A complete guide to daily and festival pujas, with mantras and step-by-step instructions in Marathi.',
    pages: 320,
    format: 'Paperback',
    year: '2022',
  },
  {
    id: 'sansk-001',
    title: 'Kavya Prakash',
    author: 'Mammata Bhatta',
    publication: 'Pradnyesh Prakashan',
    language: 'Sanskrit',
    price: 500,
    category: 'sanskrit-literature',
    coverColor: '#4A3526',
    coverAccent: '#C9A227',
    description: 'A foundational text on Sanskrit poetics (Alankara Shastra), essential for students of classical literature.',
    pages: 380,
    format: 'Hardcover',
    year: '2017',
  },
  {
    id: 'child-001',
    title: 'Bal Bharat Katha',
    author: 'Sudha Murty',
    publication: 'Pradnyesh Prakashan',
    language: 'Marathi',
    price: 280,
    category: 'childrens-spiritual',
    coverColor: '#8B7355',
    coverAccent: '#F0A850',
    description: 'Stories from Indian mythology retold for children in simple Marathi, with moral lessons.',
    pages: 160,
    format: 'Paperback',
    year: '2023',
    featured: true,
  },
  {
    id: 'spirit-001',
    title: 'Adhyatma Jnan',
    author: 'Swami Swaroopananda',
    publication: 'Pradnyesh Prakashan',
    language: 'Marathi',
    price: 400,
    category: 'spirituality',
    coverColor: '#3D2B1F',
    coverAccent: '#C0AB8E',
    description: 'An exploration of spiritual knowledge in the Marathi tradition, covering meditation, self-inquiry, and devotion.',
    pages: 300,
    format: 'Paperback',
    year: '2021',
  },
  {
    id: 'phil-001',
    title: 'Nyaya Darshana',
    author: 'Pt. Dinesh Chandra',
    publication: 'Pradnyesh Prakashan',
    language: 'Hindi',
    price: 450,
    category: 'hindu-philosophy',
    coverColor: '#2A1B12',
    coverAccent: '#B8860B',
    description: 'An introduction to the Nyaya school of Indian philosophy, covering logic, epistemology, and debate.',
    pages: 340,
    format: 'Hardcover',
    year: '2018',
  },
];

export const storeLocations: StoreLocation[] = [
  {
    name: 'Ashok Anant Nerlekar Booksellers',
    address: 'Budhwar Peth, Pune',
    city: 'Pune',
    state: 'Maharashtra',
    phone: '9309526618',
    whatsapp: '9309526618',
    email: 'nerlekarbooksellers@gmail.com',
  },
  {
    name: 'Shri Krupa Enterprises',
    address: 'Kasba Peth, Pune',
    city: 'Pune',
    state: 'Maharashtra',
    phone: '9309526618',
    whatsapp: '9309526618',
    email: 'nerlekarbooksellers@gmail.com',
  },
];

export const languages: { name: string; native: string; description: string }[] = [
  { name: 'Marathi', native: 'मराठी', description: 'The language of Maharashtra\'s saint-poets and devotional literature' },
  { name: 'Hindi', native: 'हिन्दी', description: 'The most widely spoken language of Indian spiritual texts' },
  { name: 'Sanskrit', native: 'संस्कृतम्', description: 'The ancient sacred language of the Vedas and scriptures' },
];

export const publications = ['Pradnyesh Prakashan', 'Other Publishers'];
